# Generated by Django 3.2.23 on 2024-01-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=127)),
                ('main_feature', models.CharField(choices=[('constellation', 'Constellation'), ('deep_sky', 'Deep-Sky'), ('moon', 'Moon'), ('nightscape', 'Nightscape'), ('planet', 'Planet'), ('other', '(Other)')], max_length=127)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=127)),
                ('photo_date', models.DateField()),
                ('photo_time', models.TimeField()),
                ('equipment_used', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_photo', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
