# Generated by Django 3.2.23 on 2024-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='equipment_used',
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_used',
            field=models.CharField(default='user.equipment_profile.main_camera', max_length=127),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens_used',
            field=models.CharField(default='user.equipment_profile.main_lens', max_length=127),
        ),
        migrations.AddField(
            model_name='photo',
            name='other_equipment_used',
            field=models.TextField(default='user.equipment_profile.other_equipment', max_length=127),
        ),
    ]
