# Generated by Django 3.2.23 on 2024-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='equipment',
            new_name='equipment_used',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='date_taken',
            new_name='photo_date',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='time_taken',
            new_name='photo_time',
        ),
        migrations.AlterField(
            model_name='photo',
            name='main_feature',
            field=models.IntegerField(choices=[('constellation', 'Constellation'), ('deep_sky', 'Deep-Sky'), ('moon', 'Moon'), ('nightscape', 'Nightscape'), ('planet', 'Planet'), ('other', '(Other)')]),
        ),
    ]
