# Generated by Django 3.2.23 on 2024-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20240129_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='main_feature',
            field=models.CharField(choices=[('constellation', 'Constellation'), ('deep_sky', 'Deep-Sky'), ('moon', 'Moon'), ('nightscape', 'Nightscape'), ('planet', 'Planet'), ('other', '(Other)')], max_length=127),
        ),
    ]
