# Generated by Django 3.2.23 on 2024-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20240131_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_used',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens_used',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='other_equipment_used',
            field=models.TextField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
