# Generated by Django 3.2.23 on 2024-01-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera_used',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens_used',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='photo',
            name='other_equipment_used',
            field=models.TextField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='../default_photo', upload_to='images/'),
        ),
    ]
