# Generated by Django 3.2.4 on 2024-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_main_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(blank=True),
        ),
    ]
