# Generated by Django 3.2.4 on 2024-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20240214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
