# Generated by Django 3.2.4 on 2024-02-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20240221_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_used',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens_used',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='other_equipment_used',
            field=models.TextField(blank=True, default=''),
        ),
    ]
