# Generated by Django 3.2.4 on 2024-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20240221_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(null=True),
        ),
    ]
