# Generated by Django 3.2.4 on 2024-02-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20240221_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_time',
        ),
    ]
