# Generated by Django 3.2.4 on 2024-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20240221_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
