# Generated by Django 3.2.4 on 2024-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20240221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(blank=True),
        ),
    ]
