# Generated by Django 3.2.4 on 2024-02-21 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_alter_photo_photo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
