# Generated by Django 3.2.4 on 2024-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_alter_photo_photo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_used',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens_used',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='photo',
            name='other_equipment_used',
            field=models.TextField(blank=True, default=''),
        ),
    ]
