# Generated by Django 3.2.23 on 2024-01-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='content',
            new_name='details',
        ),
    ]
