# Generated by Django 3.2.4 on 2024-02-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_camera',
            field=models.CharField(blank=True, default='No details specified', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_lens',
            field=models.CharField(blank=True, default='No details specified', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentprofile',
            name='other_equipment',
            field=models.TextField(blank=True, default='No details specified', max_length=255, null=True),
        ),
    ]
