# Generated by Django 3.2.23 on 2024-01-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentprofile',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='equipmentprofile',
            name='lens',
        ),
        migrations.AddField(
            model_name='equipmentprofile',
            name='main_camera',
            field=models.CharField(default='Main camera not yet specificed', max_length=127),
        ),
        migrations.AddField(
            model_name='equipmentprofile',
            name='main_lens',
            field=models.CharField(default='Main lens/telescope not yet specificed', max_length=127),
        ),
    ]
