# Generated by Django 3.2.23 on 2024-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_profiles', '0002_auto_20240131_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_camera',
            field=models.CharField(default='Not yet specified', max_length=127),
        ),
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_lens',
            field=models.CharField(default='Not yet specified', max_length=127),
        ),
    ]
