# Generated by Django 3.2.4 on 2024-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_profiles', '0003_auto_20240220_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_camera',
            field=models.CharField(blank=True, default='', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentprofile',
            name='main_lens',
            field=models.CharField(blank=True, default='', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentprofile',
            name='other_equipment',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
