# Generated by Django 3.2.23 on 2024-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='value',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together=set(),
        ),
    ]
